name: Ahmad JP Sawalmeh
favicon: null
layout_spectrum: 0.10436
typography_spectrum: 0.11355616897344589
title: 'yoga + plants + sound + energy '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.1875
  lightness: 0.8133722539059818
  saturation: 0.7434333830606192
  rhythmicContrast: 0.25
purpose: []
